-- 1. Upgrade Links Table for Rich Metadata
alter table links 
add column if not exists title text,
add column if not exists tags text[] default '{}',
add column if not exists favicon text,
add column if not exists archived boolean default false;

-- 2. Create Domains Table (for Multi-domain support)
create table if not exists domains (
  id bigint generated by default as identity primary key,
  domain text not null unique,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for Domains
alter table domains enable row level security;

create policy "Users can manage their own domains"
  on domains for all
  using ( auth.uid() = user_id );

-- 3. Link 'Links' to 'Domains' (Optional for now, strictly speaking we can just use text)
-- For now, let's keep it simple and just assume everything is on your default domain, 
-- but having the table ready is good.

-- 4. Create function to Auto-Fetch Title (Future Proofing)
-- We can't do HTTP requests easily from SQL, so we will handle "Title Fetching" in the frontend or Edge Function later.
